FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.3
ADD mapping.sh /utils/mapping.sh
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/e1f115e4ca285c3c24e847c4dd4be955e0ed51c2/wait-for-it.sh /utils/wait-for-it.sh
USER root
RUN chmod 755 /utils/mapping.sh
RUN chmod 755 /utils/wait-for-it.sh
USER elasticsearch
RUN bin/elasticsearch-plugin remove x-pack
RUN /usr/share/elasticsearch/bin/elasticsearch & /utils/wait-for-it.sh -t 0 localhost:9200 -- /utils/mapping.sh
CMD /usr/share/elasticsearch/bin/elasticsearch
